baseURL = "https://didosidali.github.io/website/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Sid Ali Hamideche"
theme = ""
enableRobotsTXT = true

[caches]
  [caches.assets]
    dir = ':resourceDir/_gen'
    maxAge = -1
  [caches.getcsv]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.getjson]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.getresource]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.images]
    dir = ':cacheDir/images'
    maxAge = -1
  [caches.misc]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.modules]
    dir = ':cacheDir/modules'
    maxAge = -1

[params]
  github = "https://github.com/didosidali"
  linkedin = "https://www.linkedin.com/in/sid-ali-hamideche-350071151/"
  scholar = "https://scholar.google.com/citations?user=LU-eHeYAAAAJ&hl=fr"
  email = "sid-ali.hamideche@protonmail.com"
  tagline = "Data Scientist • Machine Learning • Full-Stack Dev"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content/en"
    [languages.en.params]
      name = "Sid Ali Hamideche"
      resumeName = "resume_en.pdf"
      description = "I'm a passionate developer with a PhD degree in computer science. My main area of expertise is in data processing and training machine learning models. I also have expertise in building tools, including AI tools, REST APIs, and web interfaces, among others. Let's connect and collaborate on exciting projects!"

      [[languages.en.params.experience]]
        title = "Research Engineer & PhD candidate"
        company = "Nokia Bell Labs & University of Rennes"
        location = "Massy/Nozay/Rennes, France"
        period = "June 2020 - Decemeber 2024"
        description = "Context-aware mobile networks, Beyond 5G, 6G, AI/ML enhanced mobile networks, Deep Learning"

      [[languages.en.params.experience]]
        title = "Software Engineer"
        company = "Altim France"
        location = "Boulogne-Billancourt, France"
        period = "November 2019 - January 2020"
        description = ""

      [[languages.en.params.experience]]
        title = "Computer vision and machine learning Internship"
        company = "VEDECOM"
        location = "Versailles, France"
        period = "March 2019 - September 2019"
        description = "Unsupervised and self-supervised obstacle detection in the context of self-driving cars"

      [[languages.en.params.experience]]
        title = "R&D Engineer"
        company = "HB Technologies"
        location = "Algiers, Algeria"
        period = "June 2019 - August 2019"
        description = ""

      [[languages.en.params.experience]]
        title = "Image processing internship"
        company = "Laboratoire de Recherche en Intelligence Artificielle (LRIA)"
        location = "Algiers, Algeria"
        period = "February 2017 - June 2017"
        description = ""

      [[languages.en.params.experience]]
        title = "Image processing internship"
        company = "Laboratoire de Recherche en Intelligence Artificielle (LRIA)"
        location = "Algiers, Algeria"
        period = "February 2015 - June 2015"
        description = ""

      [[languages.en.params.education]]
        degree = "PhD in computer science (BAC+8): Machine learning, Context-aware networks, 5G networks and beyond"
        school = "Nokia Bell Labs & University of Rennes"
        location = "Massy/Nozay/Rennes, France"
        period = "2020 – 2024"
       
      [[languages.en.params.education]]
        degree = "Master's (BAC+5) in Machine learning, Information and Content (AIC)"
        school = "Paris-Saclay University"
        location = "Orsay, France"
        period = "2018 – 2019"

      [[languages.en.params.education]]
        degree = "Master's (BAC+5) intelligent computer systems (Systèmes Informatiques Intelligents)"
        school = "University of Sciences and Technology Houari Boumediene"
        location = "Algiers, Algeria"
        period = "2015 – 2017"

      [[languages.en.params.education]]
        degree = "Bachelor’s Degree (BAC+3) in Information systems and software engineering (Ingénierie des Systèmes d'Information et des Logiciels)"
        school = "University of Sciences and Technology Houari Boumediene"
        location = "Algiers, Algeria"
        period = "2012 – 2015"


  [languages.fr]
    languageName = "Français"
    weight = 2
    contentDir = "content/fr"
    [languages.fr.params]
      name = "Sid Ali HAMIDECHE"
      resumeName = "resume_fr.pdf"
      description = "Je suis un développeur passionné, titulaire d'un doctorat en informatique. Mon principal domaine d'expertise est le traitement des données et l'entraînement des modèles d'apprentissage automatique. J'ai également une expertise dans le développement d'outils, y compris les outils d'IA, les API REST et les interfaces web, entre autres. Prenons contact et collaborons sur des projets passionnants !"

      [[languages.fr.params.experience]]
        title = "Ingénieur de recherche & doctorant"
        company = "Nokia Bell Labs & Université de Rennes"
        location = "Massy/Nozay/Rennes, France"
        period = "Juin 2020 - Décembre 2024"
        description = "Réseaux mobiles sensibles au contexte, Au-delà de la 5G, 6G, Réseaux mobiles améliorés par l'IA/ML, Apprentissage profond"

      [[languages.fr.params.experience]]
        title = "Ingénieur logiciel"
        company = "Altim France"
        location = "Boulogne-Billancourt, France"
        period = "Novembre 2019 - Janvier 2020"
        description = ""

      [[languages.fr.params.experience]]
        title = "Stage en vision par ordinateur et apprentissage automatique"
        company = "VEDECOM"
        location = "Versailles, France"
        period = "Mars 2019 - Septembre 2019"
        description = "Détection d'obstacles non supervisée et auto-supervisée dans le contexte des voitures autonomes"

      [[languages.fr.params.experience]]
        title = "Ingénieur R&D"
        company = "HB Technologies"
        location = "Alger, Algérie"
        period = "Juin 2019 - Août 2019"
        description = ""

      [[languages.fr.params.experience]]
        title = "Stage en traitement d'images"
        company = "Laboratoire de Recherche en Intelligence Artificielle (LRIA)"
        location = "Alger, Algérie"
        period = "Février 2017 - Juin 2017"
        description = ""

      [[languages.fr.params.experience]]
        title = "Stage en traitement d'images"
        company = "Laboratoire de Recherche en Intelligence Artificielle (LRIA)"
        location = "Alger, Algérie"
        period = "Février 2015 - Juin 2015"
        description = ""

      [[languages.fr.params.education]]
        degree = "Doctorat en informatique (BAC+8) : Apprentissage automatique, Réseaux sensibles au contexte, Réseaux 5G et au-delà"
        school = "Nokia Bell Labs & Université de Rennes"
        location = "Massy/Nozay/Rennes, France"
        period = "2020 – 2024"

      [[languages.fr.params.education]]
        degree = "Master (BAC+5) en apprentissage automatique, Information et Contenu (AIC)"
        school = "Université Paris-Saclay"
        location = "Orsay, France"
        period = "2018 – 2019"

      [[languages.fr.params.education]]
        degree = "Master (BAC+5) en Systèmes Informatiques Intelligents"
        school = "Université des Sciences et de la Technologie Houari Boumediene"
        location = "Alger, Algérie"
        period = "2015 – 2017"

      [[languages.fr.params.education]]
        degree = "Licence (BAC+3) en systèmes d'information et ingénierie des logiciels (Ingénierie des Systèmes d'Information et des Logiciels)"
        school = "Université des Sciences et de la Technologie Houari Boumediene"
        location = "Alger, Algérie"
        period = "2012 – 2015"
